force-app/main/default/objects/EndpointService__mdt/EndpointService__mdt.object-meta.xml
<CustomObject>
    <description>Service for endpoints.</description>
    <label>Endpoint service</label>
    <pluralLabel>Endpoint services</pluralLabel>
</CustomObject>

force-app/main/default/objects/EndpointService__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The path refer to this endpoint.</description>
    <inlineHelpText>The path refer to this endpoint.</inlineHelpText>
    <label>Endpoint</label>
    <referenceTo>Endpoint__mdt</referenceTo>
    <relationshipLabel>Endpoint services</relationshipLabel>
    <relationshipName>EndpointServices</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Represent what will be the type of the request, like: GET, POST, PATH, UPDATE, DELETE.</description>
    <inlineHelpText>Represent what will be the type of the request, like: GET, POST, PATH, UPDATE, DELETE.</inlineHelpText>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>Path for the current service.</description>
    <inlineHelpText>Path for the current service.</inlineHelpText>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EndpointServiceSelectorTest.cls
@isTest
class EndpointServiceSelectorTest
{
    @isTest
    static void getTest()
    {
        List<EndpointService__mdt> endpointServiceList0 = EndpointService__mdt.getAll().values();
        System.assert(!endpointServiceList0.isEmpty(), 'No record for this medata was found: EndpointService__mdt.');
        EndpointService__mdt record = endpointServiceList0.get(0);

        Test.startTest();
        List<EndpointService__mdt> endpointServiceList1 = EndpointServiceSelector.getInstance().get(new Set<String> { record.DeveloperName });
        Test.stopTest();

        System.assert(!endpointServiceList1.isEmpty(), 'No record was found for this developername: ' + record.DeveloperName);

        EndpointService__mdt endpointServiceRecord = endpointServiceList1.get(0);
        System.assertEquals(record.DeveloperName, endpointServiceRecord.DeveloperName);
        System.assertEquals(record.Path__c, endpointServiceRecord.Path__c);
        System.assertEquals(record.Method__c, endpointServiceRecord.Method__c);
        System.assertEquals(record.Endpoint__c, endpointServiceRecord.Endpoint__c);
    }
}