force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <description>Represents holidays for the current year.</description>
    <label>National Holidays</label>
    <nameField>
        <label>National Holidays Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Represent the date for the holiday.</description>
    <inlineHelpText>Represent the date for the holiday.</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/TaskTriggerHandler.cls
public inherited sharing class TaskTriggerHandler
{
    public static void checkHolidays(List<Task> taskList)
    {
        Set<Integer> yearSet = new Set<Integer>();
        for(Task record : taskList)
        {
            if(record.ActivityDate != null)
            {
                yearSet.add(record.ActivityDate.year());
            }
        }
        
        List<National_Holidays__c> nationalHolidaysList = NationalHolidaysSelector.getInstance().getByYear(yearSet);
        Set<Date> existHolidays = new Set<Date>();
        for(National_Holidays__c record : nationalHolidaysList)
        {
            if(record.Date__c != null)
            {
                existHolidays.add(record.Date__c);
            }
        }

        for(Task record : taskList)
        {
            if(record?.ActivityDate != null && existHolidays.contains(record.ActivityDate))
            {
                record.IsHoliday__c = true;
            }
        }
    }
}