force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <description>Represents holidays for the current year.</description>
    <label>National Holidays</label>
    <nameField>
        <label>National Holidays Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Represent the date for the holiday.</description>
    <inlineHelpText>Represent the date for the holiday.</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Holidays__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Represent if the holiday is national or local.</description>
    <inlineHelpText>Represent if the holiday is national or local.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/NationalHolidaysSelector.cls
public without sharing class NationalHolidaysSelector {
    private static NationalHolidaysSelector INSTANCE
    {
        private set;
        private get
        {
            if(NationalHolidaysSelector.INSTANCE == null)
            {
                NationalHolidaysSelector.INSTANCE = new NationalHolidaysSelector();
            }
            return NationalHolidaysSelector.INSTANCE;
        }
    }

    private NationalHolidaysSelector() {}

    public static NationalHolidaysSelector getInstance()
    {
        return NationalHolidaysSelector.INSTANCE;
    }

    public List<National_Holidays__c> getByYear(Set<Integer> yearSet)
    {
        Integer year = System.now().year();
        List<National_Holidays__c> nationalHolidaysList = [
            SELECT Name, Date__c, Type__c
            FROM National_Holidays__c
            WHERE CALENDAR_YEAR(Date__c) = :yearSet
        ];
        return nationalHolidaysList;
    }
}