force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <description>Represents holidays for the current year.</description>
    <label>National Holidays</label>
    <nameField>
        <label>National Holidays Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Represent the date for the holiday.</description>
    <inlineHelpText>Represent the date for the holiday.</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Holidays__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Represent if the holiday is national or local.</description>
    <inlineHelpText>Represent if the holiday is national or local.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskTriggerTest.cls
@isTest
class TaskTriggerTest {
    @TestSetup
    static void setup()
    {
        National_Holidays__c holiday1 = new National_Holidays__c(
            Name='Carnaval 1',
            Date__c=System.today().addDays(1),
            Type__c='National'
        );
        insert holiday1;
    }

    @isTest
    static void insertTest()
    {
        Task newTask = new Task(
            Status='Not Started',
            Subject='Other',
            ActivityDate=System.today().addDays(1),
            Priority='Normal',
            OwnerId=UserInfo.getUserId()
        );

        Test.startTest();
        insert newTask;
        Test.stopTest();

        List<Task> taskList = [SELECT Id, IsHoliday__c FROM Task];
        System.assert(!taskList.isEmpty());
        System.assert(taskList.get(0).IsHoliday__c);
    }

    @isTest
    static void updateTest()
    {
        Task newTask = new Task(
            Status='Not Started',
            Subject='Other',
            Priority='Normal',
            OwnerId=UserInfo.getUserId()
        );
        insert newTask;

        List<Task> taskList = [SELECT Id, IsHoliday__c FROM Task];
        System.assert(!taskList.isEmpty());
        System.assert(!taskList.get(0).IsHoliday__c);

        newTask.ActivityDate=System.today().addDays(1);

        Test.startTest();
        update newTask;
        Test.stopTest();

        List<Task> taskList1 = [SELECT Id, IsHoliday__c FROM Task];
        System.assert(!taskList1.isEmpty());
        System.assert(taskList1.get(0).IsHoliday__c);
    }
}