force-app/main/default/objects/National_Holidays__c/National_Holidays__c.object-meta.xml
<CustomObject>
    <description>Represents holidays for the current year.</description>
    <label>National Holidays</label>
    <nameField>
        <label>National Holidays Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>National Holidays</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/National_Holidays__c/fields/Date__c.field-meta.xml
<CustomField>
    <fullName>Date__c</fullName>
    <description>Represent the date for the holiday.</description>
    <inlineHelpText>Represent the date for the holiday.</inlineHelpText>
    <label>Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/National_Holidays__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Represent if the holiday is national or local.</description>
    <inlineHelpText>Represent if the holiday is national or local.</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>National</fullName>
            </value>
            <value>
                <fullName>Local</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/TaskTriggerHandlerTest.cls
@isTest
class TaskTriggerHandlerTest {
    @TestSetup
    static void setup()
    {
        National_Holidays__c holiday = new National_Holidays__c(
            Name='Carnaval',
            Date__c=System.today(),
            Type__c='National'
        );
        insert holiday;
    }

    @isTest
    static void checkHolidaysTest()
    {
        Task taskRecord1 = new Task(ActivityDate=System.today());
        Task taskRecord2 = new Task(ActivityDate=System.today().addDays(1));
        Test.startTest();
        TaskTriggerHandler.checkHolidays(new List<Task> { taskRecord1, taskRecord2 });
        Test.stopTest();
        System.assert(taskRecord1.IsHoliday__c);
        System.assert(!taskRecord2.IsHoliday__c);
    }
}