force-app/main/default/objects/Endpoint__mdt/Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Represent endpoint settings.</description>
    <label>Endpoint</label>
    <pluralLabel>Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Endpoint__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint to make requests.</description>
    <inlineHelpText>Endpoint to make requests.</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/EndpointService__mdt.object-meta.xml
<CustomObject>
    <description>Service for endpoints.</description>
    <label>Endpoint service</label>
    <pluralLabel>Endpoint services</pluralLabel>
</CustomObject>

force-app/main/default/objects/EndpointService__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The path refer to this endpoint.</description>
    <inlineHelpText>The path refer to this endpoint.</inlineHelpText>
    <label>Endpoint</label>
    <referenceTo>Endpoint__mdt</referenceTo>
    <relationshipLabel>Endpoint services</relationshipLabel>
    <relationshipName>EndpointServices</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Represent what will be the type of the request, like: GET, POST, PATH, UPDATE, DELETE.</description>
    <inlineHelpText>Represent what will be the type of the request, like: GET, POST, PATH, UPDATE, DELETE.</inlineHelpText>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>Path for the current service.</description>
    <inlineHelpText>Path for the current service.</inlineHelpText>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/HolidaysService.cls
public class HolidaysService
{
    public static HTTPResponse execute(String year)
    {
        List<EndpointService__mdt> endpointServiceList = EndpointServiceSelector.getInstance().get(
            new Set<String> { System.Label.EndpointServiceDevelopernameBrasilAPIHolidays }
        );
        EndpointService__mdt endpointServiceRecord = EndpointServiceHelper.getByDevelopername(
            endpointServiceList,
            System.Label.EndpointServiceDevelopernameBrasilAPIHolidays
        );
        if(endpointServiceRecord == null) { throw new HolidaysServiceException(System.Label.HolidaysServiceExceptionEndpointServiceNotFound); }
        String endpoint = formatEndpoint(endpointServiceRecord, year);
        HttpRequest request = HolidaysService.createRequest(endpoint, endpointServiceRecord.Method__c);
        HTTPResponse response = new Http().send(request);
        return response;
    }

    @TestVisible
    private static HttpRequest createRequest(String endpoint, String method)
    {
        HttpRequest request = new HttpRequest();
        request.setEndpoint(endpoint);
        request.setMethod(method);
        return request;
    }
    
    @TestVisible
    private static String formatEndpoint(EndpointService__mdt endpointServiceRecord, String year)
    {
        String path = String.format(endpointServiceRecord.Path__c, new String[] { year });
        String endpoint = endpointServiceRecord.Endpoint__r.Endpoint__c + path;
        return endpoint;
    }

    public class HolidaysServiceException extends Exception {}
}