force-app/main/default/objects/Endpoint__mdt/Endpoint__mdt.object-meta.xml
<CustomObject>
    <description>Represent endpoint settings.</description>
    <label>Endpoint</label>
    <pluralLabel>Endpoints</pluralLabel>
</CustomObject>

force-app/main/default/objects/Endpoint__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>Endpoint to make requests.</description>
    <inlineHelpText>Endpoint to make requests.</inlineHelpText>
    <label>Endpoint</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/EndpointService__mdt.object-meta.xml
<CustomObject>
    <description>Service for endpoints.</description>
    <label>Endpoint service</label>
    <pluralLabel>Endpoint services</pluralLabel>
</CustomObject>

force-app/main/default/objects/EndpointService__mdt/fields/Endpoint__c.field-meta.xml
<CustomField>
    <fullName>Endpoint__c</fullName>
    <description>The path refer to this endpoint.</description>
    <inlineHelpText>The path refer to this endpoint.</inlineHelpText>
    <label>Endpoint</label>
    <referenceTo>Endpoint__mdt</referenceTo>
    <relationshipLabel>Endpoint services</relationshipLabel>
    <relationshipName>EndpointServices</relationshipName>
    <required>true</required>
    <type>MetadataRelationship</type>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/fields/Method__c.field-meta.xml
<CustomField>
    <fullName>Method__c</fullName>
    <description>Represent what will be the type of the request, like: GET, POST, PATH, UPDATE, DELETE.</description>
    <inlineHelpText>Represent what will be the type of the request, like: GET, POST, PATH, UPDATE, DELETE.</inlineHelpText>
    <label>Method</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>GET</fullName>
                <default>true</default>
                <label>GET</label>
            </value>
            <value>
                <fullName>POST</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/EndpointService__mdt/fields/Path__c.field-meta.xml
<CustomField>
    <fullName>Path__c</fullName>
    <description>Path for the current service.</description>
    <inlineHelpText>Path for the current service.</inlineHelpText>
    <label>Path</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EndpointServiceSelector.cls
public inherited sharing class EndpointServiceSelector
{
    private static EndpointServiceSelector INSTANCE
    {
        private set;
        private get
        {
            if(EndpointServiceSelector.INSTANCE == null)
            {
                EndpointServiceSelector.INSTANCE = new EndpointServiceSelector();
            }
            return EndpointServiceSelector.INSTANCE;
        }
    }

    private EndpointServiceSelector() {}

    public static EndpointServiceSelector getInstance()
    {
        return EndpointServiceSelector.INSTANCE;
    }

    public List<EndpointService__mdt> get(Set<String> developerNameSet)
    {
        List<EndpointService__mdt> endpointServiceList = [
            SELECT
                Path__c, Method__c, DeveloperName,
                Endpoint__r.Endpoint__c
            FROM EndpointService__mdt
            WHERE DeveloperName IN :developerNameSet
        ];
        return endpointServiceList;
    }
}